import type { LockedBuild } from '../engine/lock'

export const ANALYSIS_THREADS = 2

export interface AnalysisCfgOptions {
  logDir: string
  searchThreadsPerAnalysisThread: number
}

export function analysisConfigText(o: AnalysisCfgOptions): string {
  return [
    '# Generated by Joseki Dojo. Search limits are set per query.',
    `logDir = ${o.logDir.replaceAll('\\', '/')}`,
    'reportAnalysisWinratesAs = BLACK',
    `numAnalysisThreads = ${ANALYSIS_THREADS}`,
    `numSearchThreadsPerAnalysisThread = ${o.searchThreadsPerAnalysisThread}`,
    'nnCacheSizePowerOfTwo = 21',
    'nnMutexPoolSizePowerOfTwo = 17',
    'nnRandomize = true',
    '',
  ].join('\n')
}

/** CPU: split the logical cores between the analysis threads; GPU: 8 search threads per analysis thread. */
export function searchThreadsFor(kind: LockedBuild['kind'], logicalCores: number): number {
  return kind === 'cpu' ? Math.max(1, Math.floor(logicalCores / ANALYSIS_THREADS)) : 8
}
